### ISSUE TITLE
edittext to send?

### ISSUE THREAD

**Issue by fukemy** [phantomVK/MessageKit#4]
Hi, i just download and check your project, it's nice library i have seen, but i didnt see the edittext to input and send. Can you help?

**Comment by phantomVK** [comment]
I'm glad to see you message. EditText to input and send is not a small requirement in my mind. I'm willing to start a new project to develop, but I'm busy in recent and have no time schedule to start. Sorry.

**Comment by phantomVK** [comment]
> Hi, i just download and check your project, it's nice library i have seen, but i didnt see the edittext to input and send. Can you help?

I'm glad to see your message. EditText to input and send is not a small requirement in my mind. I'm willing to start a new project to develop, but I'm busy in recent and have no time schedule, Sorry.

This repo may help you a lot, [Jacksgong/JKeyboardPanelSwitch](https://github.com/Jacksgong/JKeyboardPanelSwitch)
